name: release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.14.x
      -
        name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF#refs/tags/v}
            echo ::set-output name=tag_name::${TAG}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: v${{ steps.prepare.outputs.tag_name }}

      -
        name: Update homebrew-tap
        uses: fopina/homebrew-tap@bump-action-v1
        with:
          token: ${{ secrets.PAT }}
          formula_class: GitGroup
          formula_file: git-group
          description: Easily clone all the repositories from a group or organization
          url: https://github.com/fopina/git-group/releases/download/v${{ steps.prepare.outputs.tag_name }}/git-group_${{ steps.prepare.outputs.tag_name }}_darwin_amd64.tar.gz
          license: MIT
          version: '${{ steps.prepare.outputs.tag_name }}'
          bin: git-group
          release: ./dist/git-group_${{ steps.prepare.outputs.tag_name }}_darwin_amd64.tar.gz
